### ISSUE TITLE
Latest commit breaks default word navigation

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-word-nav#10]
Hi Tony,

I know this isn't in stable yet, just letting you know about it.
I got the error when I set the behavior of the left Ctrl to: Default NVDA word navigation (WordNav disabled).

```log
IO - speech.speech.speak (07:45:58.736) - MainThread (11060):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - inputCore.executeGesture (07:45:59.441) - winInputHook (13260):
Input: kb(laptop):control+rightArrow
ERROR - scriptHandler.executeScript (07:45:59.448) - MainThread (11060):
error executing script: <bound method script_caret_moveByWordWordNav of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x10523FF0>> with gesture 'Ctrl+右光标'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "C:\Users\cary\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 694, in script_caret_moveByWordWordNav
    doWordMove(caretInfo, pattern, direction, wordCount)
  File "C:\Users\cary\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 841, in doWordMove
    for m in pattern.finditer(text)
             ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'finditer'
IO - inputCore.executeGesture (07:46:00.162) - winInputHook (13260):
Input: kb(laptop):NVDA+shift+control+f1
```

Thanks

**Comment by cary-rowen** [comment]
Fixed.
