### ISSUE TITLE
Word navigation in Poedit doesn't work

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-word-nav#11]
Try word navigation in the source text edit box in Poedit.

```log
IO - speech.speech.speak (11:27:13.223) - MainThread (9464):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
DEBUG - speech.manager.SpeechManager._handleIndex (11:27:14.004) - MainThread (9464):
Unknown index 1553, speech probably cancelled from main thread.
IO - inputCore.executeGesture (11:27:14.140) - winInputHook (6852):
Input: kb(laptop):control+rightArrow
ERROR - scriptHandler.executeScript (11:27:14.159) - MainThread (9464):
error executing script: <bound method script_caret_moveByWordWordNav of <NVDAObjects.Dynamic_PoeditRichEditIAccessibleRichEdit50WindowNVDAObject object at 0x013B8D50>> with gesture 'Ctrl+右光标'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "C:\Users\cary\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 687, in script_caret_moveByWordWordNav
    doWordMove(caretInfo, pattern, direction, wordCount)
  File "C:\Users\cary\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 815, in doWordMove
    wordEndInfo = moveToCodePointOffset(paragraphInfo, wordEndOffset)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cary\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 749, in moveToCodePointOffset
    raise e
  File "C:\Users\cary\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 744, in moveToCodePointOffset
    return textInfo.moveToCodepointOffset(offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "textInfos\__init__.pyc", line 824, in moveToCodepointOffset
RuntimeError: Inner textInfo text ' lock' doesn't match outer textInfo text 'Toggle input lock
'
IO - inputCore.executeGesture (11:27:15.052) - winInputHook (6852):
Input: kb(laptop):NVDA+shift+control+f1
```

**Comment by cary-rowen** [comment]
cc @mltony

**Comment by mltony** [comment]
I think I just fixed that - and pushed 1 commit. Could you test from the repo to see if that works for you?

**Comment by cary-rowen** [comment]
Yes, this has been fixed.
Thanks @mltony
