### ISSUE TITLE
Error when navigating in Word or PowerPoint

### ISSUE THREAD

**Issue by CyrilleB79** [mltony/nvda-word-nav#18]
### Issue
Word navigation does not work in Word nor in PowerPoint slideshow: the cursor does not move and there is no speech feedback. 
Errors are logged:

### Logged errors
1. In Word, browse mode off, no UIA:

```
ERROR - scriptHandler.executeScript (13:55:23.800) - MainThread (15672):
error executing script: <bound method script_caret_moveByWordWordNav of <NVDAObjects.Dynamic_EditableTextLogContainerWinwordWordDocumentWordDocumentIAccessibleWindowNVDAObject object at 0x0542DEF0>> with gesture 'contrôle+flèche gauche'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 697, in script_caret_moveByWordWordNav
    doWordMove(caretInfo, pattern, direction, wordCount)
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 843, in doWordMove
    wordEndInfo = moveToCodePointOffset(paragraphInfo, wordEndOffset)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 777, in moveToCodePointOffset
    raise e
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 772, in moveToCodePointOffset
    return textInfo.moveToCodepointOffset(offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "textInfos\__init__.pyc", line 862, in moveToCodepointOffset
  File "NVDAObjects\window\winword.pyc", line 1126, in collapse
RuntimeError
```

2. In Word, browse mode on, no UIA:
```
ERROR - scriptHandler.executeScript (13:58:22.508) - MainThread (15672):
error executing script: <bound method script_caret_moveByWordWordNav of <NVDAObjects.window.winword.WordDocumentTreeInterceptor object at 0x0930B2F0>> with gesture 'contrôle+flèche gauche'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 697, in script_caret_moveByWordWordNav
    doWordMove(caretInfo, pattern, direction, wordCount)
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 843, in doWordMove
    wordEndInfo = moveToCodePointOffset(paragraphInfo, wordEndOffset)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 777, in moveToCodePointOffset
    raise e
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 772, in moveToCodePointOffset
    return textInfo.moveToCodepointOffset(offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "textInfos\__init__.pyc", line 862, in moveToCodepointOffset
  File "treeInterceptorHandler.pyc", line 241, in collapse
  File "NVDAObjects\window\winword.pyc", line 1126, in collapse
RuntimeError

```

3. In PowerPoint slideshow:
```
ERROR - scriptHandler.executeScript (14:00:13.658) - MainThread (15672):
error executing script: <bound method script_caret_moveByWordWordNav of <appModules.powerpnt.ReviewableSlideshowTreeInterceptor object at 0x0AA5E4F0>> with gesture 'contrôle+flèche droite'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 658, in script_caret_moveByWordWordNav
    blacklisted = isBlacklistedApp(obj)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\wordNav\globalPlugins\wordNav.py", line 522, in isBlacklistedApp
    appName = focus.appModule.appName
              ^^^^^^^^^^^^^^^
AttributeError: 'ReviewableSlideshowTreeInterceptor' object has no attribute 'appModule'
```

### Versions
* NVDA 2024.4beta4.
* WordNav 2.2.2
* Windows 10 22H2 (AMD64) build 19045.4894
* Office 2016

### When resolving the issue
Take care to test with UIA on / off, browse mode on / off. Thanks!

**Comment by mltony** [comment]
@CyrilleB79,
So the first two exceptions are manifestations of this problem in NVDA:
https://github.com/nvaccess/nvda/issues/16172
I never had time to look deeper into this one as I don't use Word much. Moreover it seems that switching to UIA mode in word can be used as a workaround. But yeah, it doesn't make any sense that you can't collapse a textInfo in MS Word.
I think I just fixed the third exception and pushed 1 commit in master branch. Could you check if the problem goes away?

**Comment by CyrilleB79** [comment]
Yes, this seems OK now in PowerPoint with this new commit. Thanks.
